[package]
name = "bitcoinrpc"
version = "0.2.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
repository = "https://github.com/jeandudey/rust-bitcoin-rpc"
homepage = "https://github.com/jeandudey/rust-bitcoin-rpc"
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "http://docs.rs/bitcoin-rpc/"
description = "Bitcoin Rpc API client for rust."

[dependencies]
jsonrpc-client-core = "0.5.0"
jsonrpc-client-http = "0.5.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = { version = "1.0.30", features = ["arbitrary_precision"] }
hyper = "0.11.27"
