[package]
name = "bitcoinrpc"
version = "0.2.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
repository = "https://github.com/jeandudey/rust-bitcoin-rpc"
homepage = "https://github.com/jeandudey/rust-bitcoin-rpc"
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "http://docs.rs/bitcoin-rpc/"
description = "Bitcoin Rpc API client for rust."

[dependencies]
jsonrpc-client-core = { git = "https://github.com/DR-BoneZ/jsonrpc-client-rs.git", features = ["disable_version_check"] }
jsonrpc-client-http = { git = "https://github.com/DR-BoneZ/jsonrpc-client-rs.git" }
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = { version = "1.0.24", features = ["arbitrary_precision"] }
hyper = "0.11.27"
