[package]
name = "bitcoin-rpc"
version = "0.2.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
repository = "https://github.com/jeandudey/rust-bitcoin-rpc"
homepage = "https://github.com/jeandudey/rust-bitcoin-rpc"
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "http://docs.rs/bitcoin-rpc/"
description = "Bitcoin Rpc API client for rust."

[dependencies]
jsonrpc-v1 = "0.1.0"
strason = "0.3"
serde = "0.6"
